export const APPLICATION_STATUSES = {
  DRAFT: 'DRAFT',
  SUBMITTED: 'SUBMITTED',
  DOCUMENTS_PENDING: 'DOCUMENTS_PENDING',
  UNDER_VERIFICATION: 'UNDER_VERIFICATION',
  PARTNER_PROCESSING: 'PARTNER_PROCESSING',
  APPROVED: 'APPROVED',
  REJECTED: 'REJECTED',
  DISBURSED: 'DISBURSED',
  CANCELLED: 'CANCELLED',
} as const;

export const LEDGER_STATUSES = {
  PENDING: 'PENDING',
  APPROVED: 'APPROVED',
  PAYABLE: 'PAYABLE',
  PAID: 'PAID',
  REVERSED: 'REVERSED',
  CLAWBACK: 'CLAWBACK',
} as const;
